![](https://assets.qlik.com/image/upload/w_1600/q_auto/qlik/glossary/augmented-analytics/seo-hero-machine-learning-vs-ai_kls4c0.png)

# Machine Learning

![](https://techsavvypriya.wordpress.com/wp-content/uploads/2019/12/3.png)

![](https://miro.medium.com/1*o96SYcjMCcAWFOY8oHdyCQ.jpeg)

![](https://media.geeksforgeeks.org/wp-content/uploads/20231121154747/Supervised-learning.png)

![](https://miro.medium.com/1*S2EMecAq18n9lkdNhmh8AQ.jpeg)

![](https://ml-ops.org/img/ml-engineering.jpg)

In [1]:
# 100 questions with answers.

# Training: 80 questions with answers.

# Testing: 20 questions without answers to the students.

Data Preprocessing
- Handling Null and Missing Values
- Exploratory Data Analysis
- Handling Outliers
- Feature Encoding (Converting texts to numeric values)


![](https://microbenotes.com/wp-content/uploads/2019/03/Nominal-Ordinal-Interval-and-Ratio-Data.jpg)

# Data Encoding:

1. Label Encoding: Assigns integers to categories (ordinal data)
2. One-Hot Encoding: Creates binary column for each category of the categorical column
3. Ordinal Encoding
4. Target Encoding

![](https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F25e58739-0a9f-42ab-bba6-f932cee49139_962x1120.gif)

![](https://media.licdn.com/dms/image/v2/C5612AQG2g02__iAnCw/article-inline_image-shrink_1000_1488/article-inline_image-shrink_1000_1488/0/1604114785798?e=1767225600&v=beta&t=HQoWNdt8UdNeeokErEAFH-BrpIhVeLX6OPJ24Q3OKcI)

In [2]:
import pandas as pd
import numpy as np


df = pd.read_csv('./data/titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
# !pip install scikit-learn

In [4]:
# Label Encoder in Sklearn
# https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html


from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Sex_le'] = le.fit_transform(df['Sex'])

df['Embarked_le'] = le.fit_transform(df['Embarked'])

df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Sex_le  Embarked_le  
0      0         A/5 21171   7.2500   NaN        S       1            2  
1      0          PC 17599  71.2833   C85        C       0            0  
2      0  STON/O2. 3101282   7.9250   NaN        S       0            2  
3      0            113803  53.1000  C123        S       0            2  
4      0            373450   8.0500   NaN        S       1            2

In [5]:
# Ordinal Encoder in Sklearn
# https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OrdinalEncoder.html

from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()
df['Sex_oe'] = oe.fit_transform(df[['Sex']])
df['Embarked_oe'] = oe.fit_transform(df[['Embarked']])

df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Sex_le  Embarked_le  \
0      0         A/5 21171   7.2500   NaN        S       1            2   
1      0          PC 17599  71.2833   C85        C       0            0   
2      0  STON/O2. 3101282   7.9250   NaN        S       0            2   
3      0            113803  53.1000  C123        S       0            2   
4      0            373450   8.0500   NaN        S       1            2   

   Sex_oe  Embarked_oe  
0     1.0          2.0  
1     0.0          0.0  
2     0.0          2.0  
3     0.0          2.0  
4     1.0          2.0

In [6]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [7]:
e_map = {'S': 10, 'C': 20, 'Q': 30}

df['Embarked_map'] = df['Embarked'].map(e_map)

df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Sex_le  Embarked_le  \
0      0         A/5 21171   7.2500   NaN        S       1            2   
1      0          PC 17599  71.2833   C85        C       0            0   
2      0  STON/O2. 3101282   7.9250   NaN        S       0            2   
3      0            113803  53.1000  C123        S       0            2   
4      0            373450   8.0500   NaN        S       1            2   

   Sex_oe  Embarked_oe  Embarked_map  
0     1.0          2.0          10.0  
1     0.0          0.0          20.0  
2     0.0          2.0          10.0  
3     0.0          2.0          10.0  
4     1.0          2.0          10.0

In [8]:
embarked_target_mean = df.groupby('Embarked')['Survived'].mean()
print(embarked_target_mean)

df['Embarked_tm'] = df['Embarked'].map(embarked_target_mean)

df.head()

Embarked
C    0.553571
Q    0.389610
S    0.336957
Name: Survived, dtype: float64


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Sex_le  Embarked_le  \
0      0         A/5 21171   7.2500   NaN        S       1            2   
1      0          PC 17599  71.2833   C85        C       0            0   
2      0  STON/O2. 3101282   7.9250   NaN        S       0            2   
3      0            113803  53.1000  C123        S       0            2   
4      0            373450   8.0500   NaN        S       1            2   

   Sex_oe  Embarked_oe  Embarked_map  Embarked_tm  
0     1.0          2.0          10.0     0.336957  
1     0.0          0.0          20.0     0.553571  
2     0.0          2.0          10.0     0.336957  
3     0.0          2.0          10.0     0.336957  
4     1.0          2.0          10.0     0.336957

In [9]:
# One Hot Encoder in Sklearn
# https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html

from sklearn.preprocessing import OneHotEncoder

categorical_cols = ['Sex', 'Embarked']


df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
df_encoded.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0      1      0   
2                             Heikkinen, Miss. Laina  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0      1      0   
4                           Allen, Mr. William Henry  35.0      0      0   

             Ticket     Fare Cabin  Sex_le  Embarked_le  Sex_oe  Embarked_oe  \
0         A/5 21171   7.2500   NaN       1            2     1.0          2.0   
1          PC 17599  71.2833   C85       0            0     0.0          0.0   
2  STON/O2. 3101282   7.9250   NaN       0            2     0.0          2.0   
3            113803  53.1000  C123       0            2     0.0          2.0   
4            373450   8.0500   NaN       1            2     1.0          2.0   

   Embarked_map  Embarked_tm  Sex_male  Embarked_Q  Embarked_S  
0          10.0     0.336957      True       False        True  
1          20.0     0.553571     False       False       False  
2          10.0     0.336957     False       False        True  
3          10.0     0.336957     False       False        True  
4          10.0     0.336957      True       False        True

# Feature Scaling

Algorithms like KNN, SVM, and Neural Networks are sensitive to feature scales. Therefoere we perform feature scaling.

![](https://aiml.com/wp-content/uploads/2023/04/scaling-methods-1024x565.png)

### Min-Max Scaler
![](https://miro.medium.com/v2/resize:fit:1030/1*zuf6Ju67IgXY9QT_RSTkyw.png)

In [10]:
from sklearn.preprocessing import MinMaxScaler

data = np.array([[1, 2], [2, 4], [3, 6], [4, 8], [5, 10]]).astype(float)

mm_scaler = MinMaxScaler()
data_normalized = mm_scaler.fit_transform(data)

print("Original Data:\n", data)
print("Min-Max Normalized Data:\n", data_normalized)

Original Data:
 [[ 1.  2.]
 [ 2.  4.]
 [ 3.  6.]
 [ 4.  8.]
 [ 5. 10.]]
Min-Max Normalized Data:
 [[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [0.75 0.75]
 [1.   1.  ]]


### Max-Absolute Scaler

![](https://miro.medium.com/v2/resize:fit:1400/1*FGviCA_gRRNljXCeHexncg.png)

In [11]:
from sklearn.preprocessing import MaxAbsScaler

data = np.array([[1, 2], [2, 4], [3, 6], [4, 8], [5, 10]]).astype(float)

ma_scaler = MaxAbsScaler()
data_normalized_ma = ma_scaler.fit_transform(data)

print("Original Data:\n", data)
print("Max-Abs Normalized Data:\n", data_normalized_ma)

Original Data:
 [[ 1.  2.]
 [ 2.  4.]
 [ 3.  6.]
 [ 4.  8.]
 [ 5. 10.]]
Max-Abs Normalized Data:
 [[0.2 0.2]
 [0.4 0.4]
 [0.6 0.6]
 [0.8 0.8]
 [1.  1. ]]


### Z-Score Normalization (Standard Scaler)

![](https://estuary.dev/static/ceedd9895f950fc9c1d8adb0045f768c/b3bd6/15_Data_Normalization_Z_Score_Normalization_Formula_5762a2efbb.png)

In [12]:
from sklearn.preprocessing import StandardScaler

data = np.array([[1, 2], [2, 4], [3, 6], [4, 8], [5, 10]]).astype(float)

ss_scaler = StandardScaler()
data_normalized_ss = ss_scaler.fit_transform(data)

print("Original Data:\n", data)
print("Standard Scaled Data:\n", data_normalized_ss)

Original Data:
 [[ 1.  2.]
 [ 2.  4.]
 [ 3.  6.]
 [ 4.  8.]
 [ 5. 10.]]
Standard Scaled Data:
 [[-1.41421356 -1.41421356]
 [-0.70710678 -0.70710678]
 [ 0.          0.        ]
 [ 0.70710678  0.70710678]
 [ 1.41421356  1.41421356]]


### Robust Scaler

![](https://miro.medium.com/v2/resize:fit:1400/0*-uWardbsPinoWgDQ)

In [13]:
from sklearn.preprocessing import RobustScaler

data = np.array([[1, 2], [2, 4], [3, 6], [4, 8], [5, 10]]).astype(float)

rs_scaler = RobustScaler()
data_normalized_rs = rs_scaler.fit_transform(data)

print("Original Data:\n", data)
print("Robust Scaled Data:\n", data_normalized_rs)

Original Data:
 [[ 1.  2.]
 [ 2.  4.]
 [ 3.  6.]
 [ 4.  8.]
 [ 5. 10.]]
Robust Scaled Data:
 [[-1.  -1. ]
 [-0.5 -0.5]
 [ 0.   0. ]
 [ 0.5  0.5]
 [ 1.   1. ]]


## Training Phase

#### Train-Test Split

In [15]:
# Train Test Split in Sklearn
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split


from sklearn.model_selection import train_test_split

# Generate Sample data
X = np.random.randn(1000, 5) # Features
y = np.random.randint(0, 2, 1000) # Binary Target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)
print("First 5 X_train rows:\n", X_train[:5])
print("First 5 X_test rows:\n", X_test[:5])
print("First 5 y_train values:", y_train[:5])
print("First 5 y_test values:", y_test[:5])

X_train shape: (800, 5)
X_test shape: (200, 5)
y_train shape: (800,)
y_test shape: (200,)
First 5 X_train rows:
 [[-1.17348125  0.24963138 -1.13023497 -0.03503349 -1.64223469]
 [ 1.29832552  0.43209337 -0.25648935 -0.83119492 -0.98624407]
 [-1.19837588  0.43047439  0.12539148 -1.10745097 -0.13420331]
 [-0.3200348  -0.16241543  0.06580601  0.7554577   0.78165389]
 [ 0.37876701 -1.33819779  0.34271799 -0.01887426 -0.09164609]]
First 5 X_test rows:
 [[-0.19170082  0.93480496 -0.77573585 -1.25120889  0.73062277]
 [ 0.22926419  0.23684366 -0.50466577 -0.19143575  1.11254907]
 [ 1.15052185 -0.62538399  0.17568708 -1.07240409 -1.77991137]
 [ 0.21853727 -1.18372038  0.53112994 -0.3541867   0.03170056]
 [ 0.69806001  1.87280938  0.36760289  0.9317212  -0.85747095]]
First 5 y_train values: [0 1 0 1 0]
First 5 y_test values: [1 1 0 0 0]


![](https://machinemindscape.com/wp-content/uploads/2024/03/Splitting-dataset-into-train-validation-and-test-set.png)

In [17]:
X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.25, random_state=42) # 0.25 x 0.8 = 0.2


print(f"Training Set: {X_train.shape}, Validation Set: {X_val.shape}, Test Set: {X_test.shape}")

Training Set: (600, 5), Validation Set: (200, 5), Test Set: (200, 5)


In [19]:
# Logistic Regression, K-Fold Cross Validation

In [1]:
# First we'll have a data.
# We have to use it to create a model (a relationship between the features and the target variable)
# We'll use that model to predict the target variable for new data points.
# We'll also need to evaluate how well our model is performing.
# For that, we will need to split our data into training and testing sets.
# In Training set, we will further split it into training and validation sets for hyperparameter tuning.
# Training Set is used to train the model.
# Validation Set is used to tune the hyperparameters of the model.
# Test Set is used to evaluate the final model performance.