Key Concepts:
* ndarray: The core data structure in Numpy (an n-dimensional array object)
* Vectorization: Performing operations on entire arrays without explicit loops
* Broadcasting: Automatic expansion of arrays to perform operations on different shapes
* Memory Efficienty: Numpy arrays are stored in contiguous memory blocks, making them faster than Python lists

In [1]:
# !pip3 install numpy
# !pip3 install pandas

In [2]:
import numpy as np
import math
import time

data_size = 100000000

# Using Python list with math.sqrt
python_data = list(range(1, data_size + 1))
start_time = time.time()
python_sqrt = [math.sqrt(x) for x in python_data]
end_time = time.time()
python_time = end_time - start_time
print(f"Python list sqrt time: {python_time:.5f} seconds")

# Using NumPy array with np.sqrt (vectorized operation)
numpy_data = np.arange(1, data_size + 1)
start_np = time.time()
numpy_sqrt = np.sqrt(numpy_data)
end_np = time.time()
numpy_time = end_np - start_np 
print(f"NumPy array sqrt time: {numpy_time:.5f} seconds")

# Summary of results
print(f"In this scenario, NumPy is approximately {python_time / numpy_time:.2f} times faster than Python list for sqrt computation.")


Python list sqrt time: 2.68191 seconds
NumPy array sqrt time: 0.14295 seconds
In this scenario, NumPy is approximately 18.76 times faster than Python list for sqrt computation.


In [3]:
numbers = [1, 2, 3, 4, 5]
print(type(numbers))  # Output: <class 'list'>

<class 'list'>


### Array Properties

In [4]:
arr1 = np.array(numbers)
print(type(arr1))  # Output: <class 'numpy.ndarray'>
print(arr1.shape)  # Output: (5,)

<class 'numpy.ndarray'>
(5,)


In [5]:
# multi dimensional arrays
arr2 = np.array([[1, 2], [3, 4]])
print(arr2)

[[1 2]
 [3 4]]


In [6]:
print(arr2.shape)  # Output: (2, 3)
print(arr2.ndim)   # Output: 2
print(arr2.dtype)  # Output: dtype('int64') or dtype('int32') depending on the system
print(arr2.size)   # Output: 6
print(arr2.itemsize)  # Output: size of each element in bytes (e.g., 8 for int64)

(2, 2)
2
int64
4
8


In [7]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
print(arr3.shape) 
print(arr3.ndim)   
print(arr3.dtype)  
print(arr3.size)   
print(arr3.itemsize)  

(2, 2, 2)
3
int64
8
8


### Creating Arrays

In [9]:
# Creating Arrays using built-in functions
zeros_array = np.zeros((5, 6)) # 3 rows and 4 columns
print("Zeros Array:\n", zeros_array) #Escape Sequence


ones_array = np.ones((2, 3, 4)) # 2 blocks, 3 rows and 4 columns
print("\n\nOnes Array:\n", ones_array)


np_arange = np.arange(10, 51, 10) # Start, Stop, Step
print("\n\nNumpy Arange:\n", np_arange)

linspace_array = np.linspace(10, 50, 5) # Start, Stop, Number of elements
print("\n\nLinspace Array:\n", linspace_array)


random = np.random.rand(3, 4) # 3 rows and 4 columns
print("\n\nRandom Array:\n", random)


# np.eye(), np.full(), np.empty()

Zeros Array:
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


Ones Array:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


Numpy Arange:
 [10 20 30 40 50]


Linspace Array:
 [10. 20. 30. 40. 50.]


Random Array:
 [[0.43705207 0.46409591 0.8535798  0.32672882]
 [0.55250516 0.68497776 0.77303929 0.78674429]
 [0.92827082 0.44363896 0.87169587 0.68795727]]


### Indexing and Slicing

In [10]:
# Array Indexing and Slicing
# arr[start:stop:step] #1D Slicing
# arr[row_slice, col_slice] #2D Slicing
# arr[block_slice, row_slice, col_slice] #3D Slicing
# arr[condition] #Boolean Indexing
# arr[indices] #Fancy Indexing

In [11]:
scores = np.array([[90, 85, 78, 92, 88],
                    [76, 81, 79, 85, 80],
                    [88, 90, 92, 94, 96],
                    [70, 75, 80, 85, 90],
                    [95, 98, 97, 96, 99],
                    [60, 65, 70, 75, 80]
])

print(scores.shape)
print(scores.ndim)

(6, 5)
2


In [12]:
print(f"Accessing the scores of the 2nd student: {scores[1]}")  # 2nd row
print(f"Accessing the score of the 3rd student in the 4th subject: {scores[2, 3]}")  # 3rd row, 4th column

Accessing the scores of the 2nd student: [76 81 79 85 80]
Accessing the score of the 3rd student in the 4th subject: 94


In [13]:
# Slicing examples
print(f"Scores of the first three students:\n{scores[0:3]}")  # First three rows

Scores of the first three students:
[[90 85 78 92 88]
 [76 81 79 85 80]
 [88 90 92 94 96]]


In [14]:
scores[:, 1:4]

array([[85, 78, 92],
       [81, 79, 85],
       [90, 92, 94],
       [75, 80, 85],
       [98, 97, 96],
       [65, 70, 75]])

In [15]:
print(scores)

print("\n")

# Boolean Indexing - students who scored >=85 in the 1st subject
condition = scores[:, 0] >= 85
print(condition) # masking
high_scorers = scores[condition]

print(f"Students who scored more than 85 in the 1st subject:\n{high_scorers}")

[[90 85 78 92 88]
 [76 81 79 85 80]
 [88 90 92 94 96]
 [70 75 80 85 90]
 [95 98 97 96 99]
 [60 65 70 75 80]]


[ True False  True False  True False]
Students who scored more than 85 in the 1st subject:
[[90 85 78 92 88]
 [88 90 92 94 96]
 [95 98 97 96 99]]


In [16]:
# Fancy Indexing - accessing specific students
student_indices = [0, 2, 4]  # 1st, 3rd, and 5th students
selected_students = scores[student_indices]
print(f"Scores of selected students (1st, 3rd, and 5th):\n{selected_students}")

Scores of selected students (1st, 3rd, and 5th):
[[90 85 78 92 88]
 [88 90 92 94 96]
 [95 98 97 96 99]]


### Array Operations and Broadcasting

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(a + b)  # Element-wise addition
print(a * b)  # Element-wise multiplication
print(b - a)  # Element-wise subtraction
print(b / a)  # Element-wise division
print(a ** 2)  # Element-wise exponentiation

[11 22 33 44]
[ 10  40  90 160]
[ 9 18 27 36]
[10. 10. 10. 10.]
[ 1  4  9 16]


In [18]:
# Broadcasting example
# Broadcasting performs operations on arrays of different shapes.
# It automatically expands the smaller array along the dimensions of the larger array so that they have compatible shapes.

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row = np.array([10, 20, 30])

# rows of matrix: 3, columns of matrix: 3
# Rows of row vector: 1, columns of row vector: 3

# Add row to each row of the matrix
result = matrix * row
print("Result of broadcasting:\n", result)

Result of broadcasting:
 [[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


### Matrix Operations

- Dot Product
- Transpose
- Matrix Inverse
- Determinant
- Eigenvalues/Eigenvectors

![](https://algebra1course.wordpress.com/wp-content/uploads/2013/02/slide11.jpg)

In [19]:
A = np.array([[4, 2, -3],
              [1, -1, 2],
              [5, 3, 0]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])


# Dot Product
dot_product1 = np.dot(A, B)
print("Dot Product of A and B:\n", dot_product1) 

dot_product2 = A @ B
print("\nDot Product of A and B using @ operator:\n", dot_product2)

Dot Product of A and B:
 [[39 36 33]
 [ 9  7  5]
 [63 55 47]]

Dot Product of A and B using @ operator:
 [[39 36 33]
 [ 9  7  5]
 [63 55 47]]


In [20]:
print(A)
print(f"Transpose of matrix A: \n{A.T}")

[[ 4  2 -3]
 [ 1 -1  2]
 [ 5  3  0]]
Transpose of matrix A: 
[[ 4  1  5]
 [ 2 -1  3]
 [-3  2  0]]


In [21]:
print(f"Inverse of matrix A: \n{np.linalg.inv(A)}")


# Verifying A * A_inv = I
A_inv = np.linalg.inv(A)
identity = A @ A_inv
print(f"\nProduct of A and its Inverse (should be Identity Matrix):\n{identity}")

Inverse of matrix A: 
[[ 0.21428571  0.32142857 -0.03571429]
 [-0.35714286 -0.53571429  0.39285714]
 [-0.28571429  0.07142857  0.21428571]]

Product of A and its Inverse (should be Identity Matrix):
[[ 1.00000000e+00 -6.93889390e-17 -2.77555756e-17]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16  1.00000000e+00]]


In [22]:
det_A = np.linalg.det(A)
print(f"\nDeterminant of matrix A: {det_A}")


Determinant of matrix A: -27.999999999999996


In [23]:
# np.mean(), np.median(), np.std(), np.var(), np.sum(), np.min(), np.max()

### Random Number Generation

Random number generation is essential for initializing weights, creating train-test splits, shuffling data, etc.

In [106]:
# import numpy as np

np.random.seed(0) # For reproducibility

uniform = np.random.rand(5) # 5 random numbers between 0 and 1
normal = np.random.randn(5) # 5 random numbers from standard normal distribution
integers = np.random.randint(1, 100, size=5) # 5 random integers between 1 and 100

print("Uniform Random Numbers:\n", uniform)
print("\nNormal Random Numbers:\n", normal)
print("\nRandom Integers:\n", integers)

Uniform Random Numbers:
 [0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]

Normal Random Numbers:
 [-0.84272405  1.96992445  1.26611853 -0.50587654  2.54520078]

Random Integers:
 [38 26 78 73 10]


In [110]:
# Generate data from specific distributions
normal_dist = np.random.normal(loc=50, scale=10, size=1000) # Mean=0, StdDev=1        
print("\nNormal Distribution Sample:\n", normal_dist)


Normal Distribution Sample:
 [46.71933421 38.54896599 52.29386412 64.78341959 61.96773302 49.37166064
 56.63762488 58.97479193 50.27434532 41.74869059 41.15790348 48.13575317
 56.33603821 43.10316571 61.69728616 43.0438949  39.7441049  34.69615272
 50.38316012 46.75937918 51.75344273 71.2690235  64.79274209 47.5598543
 49.0126058  42.62276691 50.20820601 45.20702671 47.17391859 41.05531725
 43.71140177 43.26535604 59.87417514 52.39682671 50.73791991 56.92329937
 57.94055087 33.94398655 63.28635505 38.54424881 52.82917952 48.96608677
 45.54384027 47.9977407  48.00574096 36.83758875 49.17823424 53.36534235
 36.55810697 67.66714236 46.52218729 31.00235987 46.35710551 47.11363092
 72.57423207 48.776671   52.10614653 42.28822912 64.91690923 44.97861646
 53.48123079 39.87541052 63.07705522 45.77976128 37.89507423 49.40811464
 63.33327199 51.12495043 54.05996075 61.74485626 53.21002331 45.59403523
 32.39223574 59.48456427 57.54652274 50.03208058 41.02941526 46.42386023
 43.9815968  57.422115

In [111]:
print(f"Mean: {np.mean(normal_dist)}")
print(f"Standard Deviation: {np.std(normal_dist)}")

Mean: 49.95470859747351
Standard Deviation: 9.936953427831885
