## Numpy


In [2]:
import numpy as np
import time
import math 


data_size = 10000000
list_data = list(range(1, data_size + 1))
start_time = time.time()
squared_list = [math.sqrt(x) for x in list_data]
end_time = time.time()
list_time_taken = end_time - start_time
print(f"the total time taken is {list_time_taken:.6f} seconds ")

the total time taken is 0.583283 seconds 


In [3]:
numpy_data = np.arange(1, data_size+1)
start_time = time.time()
squared_numpy = np.sqrt(numpy_data)
end_time = time.time()
numpy_data_time_taken = end_time - start_time
print(f"the total time taken is {numpy_data_time_taken:.6f} seconds ")
# Comparing performance of list comprehension vs NumPy for square root calculation
print(f"NumPy is {list_time_taken / numpy_data_time_taken:.2f} times faster than list comprehension")

the total time taken is 0.018713 seconds 
NumPy is 31.17 times faster than list comprehension


In [4]:
# different types of array creation in numpy
# two dimensional numpy array
array2 = np.array([[1,2,3], [4,5,6]])
print(array2)
print(array2.ndim)
print(array2.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [5]:
#three dimensional array
array3 = np.array([[[1,2,3], [4,5,6], [7,8,9], [3,5,6]], [[1,2,3], [3,4,5], [4,5,6], [8,9,10]]])
print(array3)
print(array3.ndim)
print(array3.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 3  5  6]]

 [[ 1  2  3]
  [ 3  4  5]
  [ 4  5  6]
  [ 8  9 10]]]
3
(2, 4, 3)


In [6]:
arr = np.arange(2 * 3 * 4 * 5).reshape(2, 3, 4, 5)

print(arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]
Shape: (2, 3, 4, 5)
Number of dimensions: 4


In [7]:
linspace_array = np.linspace(10,20, 2)
print(linspace_array)
eye_array = np.eye(2,4,2) # it creates identity matrix
print(eye_array)
full_array = np.full((2,3), 7) # creates an array filled with a specified value
print(full_array)
empty_array = np.empty((3,2)) # creates an empty array
print(empty_array)

[10. 20.]
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[7 7 7]
 [7 7 7]]
[[-6.95208261e-310  1.56437419e-223]
 [ 1.43625574e-311  1.43625574e-311]
 [ 5.43472210e-323  4.94065646e-324]]


In [8]:
#array indexing and slicing
# array[start:stop:step] 1D slicing
#arr[row_slice, col_slice] 2D slicing


In [9]:
scores = np.array([[90, 85, 78, 92, 88],
                    [76, 81, 79, 85, 80],
                    [88, 90, 92, 94, 96],
                    [70, 75, 80, 85, 90],
                    [95, 98, 97, 96, 99],
                    [60, 65, 70, 75, 80]
])

In [10]:
# accessing the first row
print(scores[1])
# accessing the first row second column
print(scores[0,1])

[76 81 79 85 80]
85


In [11]:
# slicing examples
print(scores[0:3]) # Frist three rows

# accessing columns from second to fourth
print(scores[:, 1:4])

[[90 85 78 92 88]
 [76 81 79 85 80]
 [88 90 92 94 96]]
[[85 78 92]
 [81 79 85]
 [90 92 94]
 [75 80 85]
 [98 97 96]
 [65 70 75]]


In [12]:
# boolean indexing
# we need to print the students who got more than 85 in their first subject
print(scores[scores[:, 0]>=85])

[[90 85 78 92 88]
 [88 90 92 94 96]
 [95 98 97 96 99]]


In [13]:
# Fancy indexing
# we need to print the marks of 1st, 3rd and 4th student
print(scores[[1,2]])

[[76 81 79 85 80]
 [88 90 92 94 96]]


In [14]:
# broadcasting 
# broadcasting allows numpy to perform operations on arrays of different shapes
A = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
B = np.array([10,20,30])
C = A + B
print(C)
D = A * 2
print(D)

[[11 22 33]
 [14 25 36]
 [17 28 39]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [15]:
# calculating dot product of two matrices

X = np.array([[1,3,-2],
                [-3,0,-5],
                [2,5,0]])
Y = np.array([[7,8],
                [9,10],
                [11,12]])
Z = np.dot(X, Y)
print(Z)
# we can also calculate dot product using @ operator
Z2 = X @ Y
print(Z2)

[[ 12  14]
 [-76 -84]
 [ 59  66]]
[[ 12  14]
 [-76 -84]
 [ 59  66]]


In [16]:
# for transpose of a matrix
print(X.T)
# for inverse calculation of a matrix
X_inv = np.linalg.inv(X)
identity_matrix = np.dot(X, X_inv)
print("Identity Matrix:")
print(identity_matrix)

[[ 1 -3  2]
 [ 3  0  5]
 [-2 -5  0]]
Identity Matrix:
[[ 1.00000000e+00  0.00000000e+00 -1.11022302e-16]
 [ 4.44089210e-16  1.00000000e+00 -2.22044605e-16]
 [-1.11022302e-16  1.11022302e-16  1.00000000e+00]]


In [17]:
# random number generation
np.random.seed(0)  # for reproducibility
print(np.random.rand(3,2))  # uniform distribution between 0 and 1

[[0.5488135  0.71518937]
 [0.60276338 0.54488318]
 [0.4236548  0.64589411]]
